apiVersion: v1
kind: Pod
metadata:
  name: node-hello-world
  namespace: jenkins-ns
spec:
  containers:
  - name: node-hello-world
    image: 979050235289.dkr.ecr.ap-southeast-2.amazonaws.com/node-hello-world:${BUILD_NUMBER}
    ports:
    - containerPort: 80
